"""empty message

Revision ID: 620af5b5b1d9
Revises: d57023653705
Create Date: 2020-04-18 19:22:46.065985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '620af5b5b1d9'
down_revision = 'd57023653705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_name'), 'community', ['name'], unique=True)
    op.create_table('subscription',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('priveleges', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'community_id')
    )
    op.add_column('chat', sa.Column('community_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chat', 'community', ['community_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat', type_='foreignkey')
    op.drop_column('chat', 'community_id')
    op.drop_table('subscription')
    op.drop_index(op.f('ix_community_name'), table_name='community')
    op.drop_table('community')
    # ### end Alembic commands ###
