"""empty message

Revision ID: c85c95d50f8c
Revises: 840f79f0b3c7
Create Date: 2020-04-28 19:28:43.509912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c85c95d50f8c'
down_revision = '840f79f0b3c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('apns', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'apns')
    # ### end Alembic commands ###
